#!/usr/bin/env python3
import sys
from core import set_language, run_tool

STRINGS = {
    "pause": "Entrée pour revenir au menu…",
    "open_yn": "ouvrir ? (o/n) >>",
    "yes": "Oui", "no": "Non",
    "username": "Username", "display": "Display", "created": "Créé",
    "banned": "Banni", "verified": "Vérifié", "friends": "Amis",
    "followers": "Followers", "following": "Abonnements",
    "status": "Statut", "in_game": "En jeu", "description": "Description",
    "name": "Nom", "creator": "Créateur", "price": "Prix", "sales": "Ventes",
    "playing": "En ligne", "visits": "Visites", "max_players": "Max joueurs",
    "members": "Membres", "public": "Public", "owner_id": "Owner ID",
    "assets": "Assets", "equipped": "Assets équipés",
    "status_off": "Hors ligne", "status_on": "En ligne",
    "status_game": "En jeu", "status_studio": "Studio",
    "off_sale": "Off sale",
    "invalid_cookie": "INVALID — cookie expiré ou invalide",
    "user_not_found": "Utilisateur introuvable",
    "unknown_tool": "Outil inconnu:",
    "cancelled": "annulé", "error": "Erreur:", "network": "Connexion impossible",
    "cookie_title": "ROBLOX COOKIE CHECKER",
    "cookie_desc": "Valide un cookie .ROBLOSECURITY via l'API Roblox",
    "cookie_prompt": "cookie (.ROBLOSECURITY)",
    "cookie_ok": "Cookie valide",
    "user_title": "ROBLOX USERNAME LOOKUP",
    "user_desc": "Username ou ID → profil public",
    "user_prompt": "username ou user id",
    "game_title": "ROBLOX GAME LOOKUP",
    "game_desc": "Place ID → infos jeu",
    "place_prompt": "place id",
    "place_invalid": "Place ID invalide",
    "game_not_found": "Jeu introuvable",
    "game_details_fail": "Détails jeu introuvables",
    "group_title": "ROBLOX GROUP LOOKUP",
    "group_desc": "Group ID → infos groupe public",
    "group_prompt": "group id",
    "group_invalid": "Group ID invalide",
    "group_not_found": "Groupe introuvable",
    "avatar_title": "ROBLOX AVATAR VIEWER",
    "avatar_desc": "Voir l'avatar + assets équipés",
    "robux_title": "ROBLOX ROBUX CHECKER",
    "robux_desc": "Robux du compte lié au cookie",
    "robux_fail": "Impossible de lire le solde",
    "account_title": "ROBLOX ACCOUNT CHECKER",
    "account_desc": "Analyse complète via cookie",
    "account_result": "Account Check",
    "profile_title": "ROBLOX PROFILE VIEWER",
    "profile_desc": "Profil public détaillé",
    "item_title": "ROBLOX ITEM LOOKUP",
    "item_desc": "Asset ID → détails item",
    "item_prompt": "asset / item id",
    "item_invalid": "Asset ID invalide",
    "item_not_found": "Item introuvable",
    "badge_title": "ROBLOX BADGE CHECKER",
    "badge_desc": "Badges d'un user (cookie requis)",
    "badge_fail": "Badges inaccessibles",
    "badge_empty": "Aucun badge trouvé",
    "inv_title": "ROBLOX INVENTORY VIEW",
    "inv_desc": "Limiteds / collectibles (cookie requis)",
    "inv_fail": "Inventaire inaccessible",
    "inv_empty": "Aucun collectible trouvé",
    "uid_prompt": "user id (enter = {} soi-même)",
    "uid_invalid": "User ID invalide",
    "fav_title": "ROBLOX GAME FAVORITES",
    "fav_desc": "Place ID → favoris & votes",
    "favorites": "Favoris",
    "roles_title": "ROBLOX GROUP ROLES",
    "roles_desc": "Group ID → liste des rôles",
    "limited_title": "ROBLOX LIMITED PRICE",
    "limited_desc": "Asset ID → prix limited / RAP",
    "rap": "RAP (moyenne)",
    "stock": "Stock restant",
    "friends_title": "Liste amis", "friends_desc": "Cookie requis",
    "friends_empty": "Aucun ami ou cookie invalide",
    "follow_title": "Followers", "follow_desc": "Followers / following count",
    "age_title": "Âge du compte", "age_desc": "Date de création",
    "gp_title": "Game Pass", "gp_desc": "ID game pass",
    "gamepass_id": "game pass id",
    "place_title": "Place → Universe", "place_desc": "Convertir Place ID",
    "place_id": "place id",
    "cat_title": "Catalog Search", "cat_desc": "Recherche catalogue",
    "search_q": "mot-clé",
    "multi_title": "Multi Cookie", "multi_desc": "Plusieurs cookies",
    "multi_hint": "1 cookie/ligne, ligne vide = fin",
    "export_title": "Export JSON", "export_desc": "Profil → data/exports/",
    "uid_only": "user id",
    "batch_title": "Avatars batch", "batch_desc": "IDs séparés par espaces",
    "uids_csv": "user ids",
    "gfunds_title": "Group Funds", "gfunds_desc": "Robux groupe (cookie)",
    "group_id": "group id",
    "gfunds_note": "Nécessite permissions groupe",
    "not_found": "Introuvable",
    "robux": "Robux",
}

if __name__ == "__main__":
    set_language(STRINGS)
    run_tool(sys.argv[1] if len(sys.argv) > 1 else "")
