#!/usr/bin/env python3
import sys
from core import set_language, run_tool

STRINGS = {
    "pause": "Entrée pour revenir au menu…",
    "yes": "Oui", "no": "Non", "cancelled": "Annulé", "pick_mode": "Choisir le mode",
    "error_title": "Erreur", "unknown": "Outil inconnu :", "network": "Connexion impossible",
    "file_not_found": "Fichier introuvable", "lines_hint": "1 par ligne, ligne vide pour finir",
    "name": "Nom", "type": "Type", "created": "Création",
    "pub_tag": "https://discord.gg/007tools", "pub_short": "https://discord.gg/007tools · Wock-Multi v2",
    "pub_line": "**Wock-Multi** → https://discord.gg/007tools", "pub_user": "Wock-Multi",
    "wh_title": "Webhook Info", "wh_desc": "URL webhook → salon, serveur & détails",
    "wh_prompt": "URL webhook complète", "wh_invalid": "URL webhook invalide",
    "wh_fail": "Webhook introuvable", "wh_fetch": "Récupération…",
    "wsg_title": "Send Message", "wsg_desc": "Ping test, custom, TTS, silencieux, faux user, mention, thread",
    "wsg_test": "Ping test", "wsg_custom": "Message custom", "wsg_tts": "Message TTS",
    "wsg_silent": "Silencieux (sans notif)", "wsg_fake": "Faux username/avatar", "wsg_mention": "Mention ping",
    "wsg_thread": "Thread / post forum",
    "wt_ping": "✔ Wock-Multi online — https://discord.gg/007tools",
    "wt_sending": "Envoi…", "wt_ok": "Message envoyé", "wt_fail": "Échec envoi",
    "ws_title": "Webhook Spammer", "ws_desc": "Normal, mass threads, multi-URL, mots aléatoires, embed spam",
    "ws_mode_normal": "Spam normal", "ws_mode_mass": "Mass (threads)", "ws_mode_multi": "Multi-webhook",
    "ws_mode_random": "Mots aléatoires", "ws_mode_embed": "Embed spam",
    "ws_msg": "Contenu du message", "ws_count": "Nombre (1-100, défaut 10)",
    "ws_delay": "Délai entre envois (sec, défaut 0.3)",
    "ws_name": "Nom webhook (optionnel)", "ws_mention": "Ajouter @everyone ? (oui/non)",
    "ws_running": "Envoi…", "ws_sent": "Envoyés", "ws_failed": "Échoués",
    "wgf_title": "GIF & Bad Word Spammer", "wgf_desc": "GIF embed, spam rapide, gros mots ou mix",
    "wgf_mode_gif": "Spam GIF (embed)", "wgf_mode_fast": "Spam rapide (GIF + mot)",
    "wgf_mode_bad": "Spam gros mots", "wgf_mode_mix": "Mix GIF + gros mots",
    "wgf_gifs": "URLs GIF (virgule/file ou Entrée = défaut)",
    "wgf_badwords": "Gros mots (virgule/file ou Entrée = défaut)",
    "wgf_running": "Spam en cours…",
    "wms_title": "Mass Spammer", "wms_desc": "Spam parallèle multi-threads (style PEGPX)",
    "wms_threads": "Threads (1-8, défaut 4)", "wms_per": "Messages/thread (1-25, défaut 5)",
    "wms_running": "Mass spam en cours…",
    "wmu_title": "Multi-Webhook Spam", "wmu_desc": "Spam plusieurs URLs webhook",
    "wmu_result": "Résultats multi-webhook",
    "wrs_title": "Random Spammer", "wrs_desc": "Envoie des mots aléatoires d'une liste",
    "wrs_words": "Mots (virgule/file ou Entrée = défaut)",
    "we_title": "Embed Sender", "we_desc": "Envoie un embed riche via le webhook",
    "we_embed_title": "Titre embed", "we_embed_desc": "Description embed",
    "we_color": "Couleur hex (défaut 880000)", "we_footer": "Texte footer",
    "we_thumb": "URL miniature (optionnel)", "we_default_desc": "Propulsé par Wock-Multi · https://discord.gg/007tools",
    "we_sending": "Envoi embed…", "we_ok": "Embed envoyé", "we_fail": "Échec embed",
    "wse_title": "Embed Spammer", "wse_desc": "Spam d'embeds colorés via webhook",
    "wse_running": "Envoi embeds…",
    "wj_title": "JSON Sender", "wj_desc": "Envoie un payload JSON custom au webhook",
    "wj_hint": "Coller du JSON valide (content, embeds, username…)",
    "wj_body": "Payload JSON", "wj_invalid": "JSON invalide",
    "wj_sending": "Envoi payload…", "wj_ok": "Payload envoyé", "wj_fail": "Échec envoi",
    "wf_title": "File Sender", "wf_desc": "Envoie un fichier via webhook (local ou URL)",
    "wf_source": "Chemin fichier ou URL directe", "wf_caption": "Légende (optionnel)",
    "wf_download": "Téléchargement…", "wf_ok": "Fichier envoyé", "wf_fail": "Échec envoi",
    "wtts_title": "TTS Sender", "wtts_desc": "Message text-to-speech",
    "wtts_ok": "Message TTS envoyé", "wtts_fail": "Échec TTS",
    "wmn_title": "Mention Ping", "wmn_desc": "Ping @everyone ou @here via webhook",
    "wmn_ok": "Mention envoyée", "wmn_fail": "Échec mention",
    "wg_title": "Ghost Ping", "wg_desc": "Envoie un message puis le supprime",
    "wg_msg": "Message (défaut @everyone + pub)", "wg_delay": "Supprimer après (sec, défaut 1.5)",
    "wg_fail_send": "Échec envoi", "wg_no_id": "Pas d'ID message retourné",
    "wg_wait": "Suppression dans", "wg_ok": "Ghost ping terminé", "wg_fail_del": "Échec suppression",
    "wt2_title": "Thread Sender", "wt2_desc": "Poster dans un thread via thread_id",
    "wt2_thread": "ID thread", "wt2_invalid": "ID thread invalide",
    "wt2_ok": "Posté dans le thread", "wt2_fail": "Échec post thread",
    "wem_title": "Message Editor", "wem_desc": "Modifier un message envoyé par ce webhook",
    "wem_content": "Nouveau contenu", "wem_ok": "Message modifié", "wem_fail": "Échec modification",
    "wm_title": "Message Deleter", "wm_desc": "Supprime un message envoyé par ce webhook",
    "wm_id": "ID message", "wm_id_invalid": "ID message invalide",
    "wm_confirm": "Supprimer ce message ? (oui/non)", "wm_ok": "Message supprimé", "wm_fail": "Échec suppression",
    "wx_title": "Webhook Editor", "wx_desc": "Renommer, changer avatar ou supprimer l'avatar (PATCH)",
    "wx_mode_name": "Renommer", "wx_mode_avatar": "Changer avatar", "wx_mode_clear": "Supprimer avatar",
    "wx_name": "Nouveau nom (Entrée = skip)", "wx_avatar": "URL image avatar (Entrée = skip)",
    "wx_avatar_fail": "Impossible de charger l'avatar", "wx_nothing": "Rien à modifier",
    "wx_patch": "Mise à jour…", "wx_ok": "Webhook mis à jour", "wx_fail": "Échec mise à jour",
    "wrn_title": "Rename Webhook", "wrn_desc": "Renommer rapidement via PATCH",
    "wrn_ok": "Renommé", "wrn_fail": "Échec renommage",
    "wc_title": "Webhook Cloner", "wc_desc": "Copier nom & avatar vers un autre webhook",
    "wc_source": "URL webhook source", "wc_target": "URL webhook cible",
    "wc_running": "Clonage…", "wc_ok": "Cloné", "wc_fail": "Échec clonage",
    "wc_fail_src": "Webhook source invalide",
    "wex_title": "URL Extractor", "wex_desc": "Extraire ID, token & URLs API du lien",
    "wsf_title": "Snowflake Decoder", "wsf_desc": "Décoder la date de création de l'ID webhook",
    "wsf_invalid": "ID snowflake invalide",
    "wb_title": "Bulk Checker", "wb_desc": "Valide plusieurs URLs webhook d'un coup",
    "wb_prompt": "URL ou taper file", "wb_file": "Chemin fichier .txt",
    "wb_running": "Vérification…", "wb_result": "Résultats bulk", "wb_valid": "Valides",
    "wl_title": "Webhook Library", "wl_desc": "Sauvegarder & gérer les URLs localement",
    "wl_save": "Sauvegarder", "wl_list": "Lister", "wl_remove": "Supprimer",
    "wl_label": "Nom du label", "wl_saved": "Sauvegardé", "wl_removed": "Retiré de la bibliothèque",
    "wl_not_found": "Label introuvable", "wl_empty": "Bibliothèque vide — sauvegarde un webhook",
    "wcu_title": "Curl Generator", "wcu_desc": "Génère des commandes curl pour ce webhook",
    "wcu_hint": "Copier/coller dans le terminal (attention au DELETE)",
    "wbd_title": "Bulk Destroyer", "wbd_desc": "Supprimer plusieurs webhooks d'une liste",
    "wbd_confirm": "Supprimer TOUS les webhooks listés ? (oui/non)",
    "wd_title": "Webhook Destroyer", "wd_desc": "Supprimer un webhook ou une liste en bulk",
    "wd_single": "Un webhook", "wd_bulk": "Bulk delete (liste)",
    "wd_confirm": "Supprimer ce webhook ? (oui/non)", "wd_ok": "Supprimé", "wd_fail": "Échec",
    "wav_title": "Avatar Changer", "wav_desc": "Changer l'avatar webhook (fichier ou URL, KoalaHook)",
    "wav_source": "Chemin image ou URL", "wav_ok": "Avatar mis à jour", "wav_fail": "Échec avatar",
    "wca_title": "Clear Avatar", "wca_desc": "Supprimer l'avatar du webhook",
    "wca_confirm": "Supprimer l'avatar ? (oui/non)", "wca_ok": "Avatar supprimé", "wca_fail": "Échec",
    "wef_title": "Embed Fields", "wef_desc": "Embed avec champs inline (style DisHook)",
    "wef_fields_hint": "Jusqu'à 5 champs, nom vide pour arrêter",
    "wef_fname": "Nom champ", "wef_fval": "Valeur champ", "wef_ok": "Embed envoyé", "wef_fail": "Échec",
    "wme_title": "Multi-Embed", "wme_desc": "Plusieurs embeds en un message (max 10)",
    "wme_count": "Nombre embeds (2-10, défaut 3)", "wme_ok": "Envoyé", "wme_fail": "Échec",
    "wim_title": "Impersonate Send", "wim_desc": "Username & avatar custom par message",
    "wim_avatar": "URL avatar (optionnel)", "wim_ok": "Envoyé", "wim_fail": "Échec",
    "wsi_title": "Silent Send", "wsi_desc": "Envoi sans notification (SUPPRESS_NOTIFICATIONS)",
    "wsi_ok": "Message silencieux envoyé", "wsi_fail": "Échec",
    "wmc_title": "Mentions Control", "wmc_desc": "Contrôle allowed_mentions",
    "wmc_block": "Bloquer toutes mentions", "wmc_everyone": "Autoriser @everyone",
    "wmc_here": "Autoriser @here", "wmc_all": "Autoriser tout",
    "wmc_ok": "Envoyé avec règles mentions", "wmc_fail": "Échec",
    "wrt_title": "Rate Limit Test", "wrt_desc": "rafale de requêtes → 429 / Retry-After",
    "wrt_bursts": "Rafale (3-15, défaut 8)", "wrt_result": "Test rate limit",
    "wrt_rl": "Rate limits",
    "wpy_title": "Python Generator", "wpy_desc": "Génère du code Python discord-webhook",
    "wpy_hint": "pip install discord-webhook",
    "wfl_title": "Flood Spammer", "wfl_desc": "Spam infini jusqu'à Ctrl+C (KoalaHook)",
    "wfl_hint": "Ctrl+C pour arrêter",
    "wfo_title": "Forum Thread", "wfo_desc": "Créer un post forum via thread_name",
    "wfo_name": "Titre du thread", "wfo_ok": "Post forum créé", "wfo_fail": "Échec",
    "wcr_title": "Webhook Generator", "wcr_desc": "Créer un webhook via bot token + channel ID",
    "wcr_token": "Token bot", "wcr_no_token": "Token bot requis — saisis-le dans la console",
    "wcr_channel": "ID salon", "wcr_channel_invalid": "ID salon invalide",
    "wcr_name": "Nom webhook", "wcr_ok": "Webhook créé — rejoins https://discord.gg/007tools", "wcr_fail": "Échec création",
    "wst_title": "Sticker Sender", "wst_desc": "Envoyer un sticker Discord via webhook",
    "wst_id": "ID sticker", "wst_invalid": "ID sticker invalide",
    "wst_ok": "Sticker envoyé", "wst_fail": "Échec (sticker guild/Nitro requis)",
}

if __name__ == "__main__":
    set_language(STRINGS)
    run_tool(sys.argv[1] if len(sys.argv) > 1 else "")
